Introduces a merge function that merges an array of states into a single new state
daiscog/ngx-http-request-state pull request #11
Opened 2023-03-19 12:09 UTC by PeterSR

Issue: #10 

---

This PR introduces a function `mergeStates` that allows the user to merge/flatten a list of HttpRequestState objects into a new one based on a transformer function. See the issue and updated Readme for more details.

2023-03-23 20:01 UTC, daiscog requested changes
Looks good.  One minor typo in the readme to correct.  Please also run `npm run format` to get prettier to reformat everything.

2023-03-26 07:03 UTC, PeterSR commented on libs/ngx-http-request-state/README.md
> +If an error occur in any of the requests, the merged state will be an `ErrorState`.
Nice catch!

2023-03-26 07:08 UTC, PeterSR commented
Thanks! And apologies for forgetting the formatter. 
It should be done now.

2023-04-14 15:50 UTC, daiscog approved these changes

2023-04-16 06:41 UTC, PeterSR commented
Hi @daiscog - Do I need to do anything here? :blush:

2023-04-26 08:45 UTC, merged

2023-04-26 08:46 UTC, daiscog commented
Hi @PeterSR 

Sorry for the delay - will release soon.